# serivce name
spring:
  application:
    name: account-service
  mvc:
    logResolvedException: false

module-url: /account/v1

server:
  port: 8210

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

db:
  schema: account

security:
  properties:
    jwtHeader: Service-Authorization
    jwtPrefix: JWT
    jwtSecret: CnfxFqbCKHLqzT9LGruE

# eureka server url
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka
    registry-fetch-interval-seconds: 20
    availability-zones:
      default: defaultZone
    region: default
    enabled: true
  instance:
    prefer-ip-address: true

#property to endpoint migrate
exchange:
  endpoint:
    permission:
      endpointUpdatePack: http://permission-service/endpoint/pack
    mail:
      emailVerification: http://mail-service/email/verification
      sentEmail: http://mail-service/email/single
      phoneVerification: http://mail-service/phone/single
      sendPhone: http://mail-service/phone/single

system-notification:
  corporation-delete:
    exchange-name: system-notification-corporation-delete
  signup-with-code:
    exchange-name: system-notification-signup-with-code
  update-auth-info:
    exchange-name: system-notification-update-auth-info
  update-client-info:
    exchange-name: system-notification-update-client-info

image-url:
  user:
    avatar: https://glcdn.sgp1.digitaloceanspaces.com/coupler/Avatar.png
    cover: https://glcdn.sgp1.digitaloceanspaces.com/coupler/Cover.png
  corporation:
    logo: https://glcdn.sgp1.digitaloceanspaces.com/coupler/Avatar.png
    cover: https://glcdn.sgp1.digitaloceanspaces.com/coupler/Cover.png

auth:
  sms:
    prefix: 'Code:'

demo:
  phone: '380888080808'
  code: '808080'
