spring:
  # datasource configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: ${db.schema}
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true

  # Flyway configuration
  flyway:
    enabled: true
    locations: classpath:db/migration/all
    baseline-version: 1
    sql-migration-suffixes: .sql
    sql-migration-prefix: V
    schemas: ${db.schema}

  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
    queue-logstash: logstash

cdn:
  properties:
    accessKey: XJSIQ6UA5HZEHMH3DDUP
    secretKey: C5PSCSJgAG4VaCYUSJaK9SA/pDHX/kE7BLatMHEz90I
    host: sgp1.digitaloceanspaces.com
    region: sgp1
    bucket: glcdn
    folder: karma

