spring:
  # datasource configuration
  datasource:
    url: jdbc:postgresql://46.101.182.178:26780/glsdev
    username: postgres
    password: GliesereumAdmin0013
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: ${db.schema}
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true

  # Flyway configuration
  flyway:
    enabled: true
    locations: classpath:db/migration/all
    baseline-version: 1
    sql-migration-suffixes: .sql
    sql-migration-prefix: V
    schemas: ${db.schema}

  rabbitmq:
    host: 207.154.239.122
    port: 5672
    password: Af2f4dsASF
    username: rabbit
    connection-timeout: 5s
    queue-logstash-system: logstash-system
    queue-logstash-request: logstash-request
    queue-mail: verificationQueue

swagger:
  enable: true

cdn:
  properties:
    accessKey: XJSIQ6UA5HZEHMH3DDUP
    secretKey: C5PSCSJgAG4VaCYUSJaK9SA/pDHX/kE7BLatMHEz90I
    host: sgp1.digitaloceanspaces.com
    region: sgp1
    bucket: glcdn
    folder: karma
