spring:
  # datasource configuration
  datasource:
    url: jdbc:postgresql://${db.host}:${db.port}/${db.database}
    username: ${db.username}
    password: ${db.password}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: ${db.schema}
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: false

  # Flyway configuration
  flyway:
    enabled: true
    locations: classpath:db/migration/all
    baseline-version: 1
    sql-migration-suffixes: .sql
    sql-migration-prefix: V
    schemas: ${db.schema}

  rabbitmq:
    host: ${rabbit.host}
    port: ${rabbit.port}
    password: ${rabbit.password}
    username: ${rabbit.user}
    connection-timeout: 5s
    queue-logstash-system: LOG_SYSTEM_QUEUE
    queue-logstash-request: LOG_REQUEST_QUEUE

cdn:
  properties:
    accessKey: ${cdn.accessKey}
    secretKey: ${cdn.secretKey}
    host: ${cdn.host}
    region: ${cdn.region}
    bucket: ${cdn.bucket}
    folder: ${cdn.folder}