version: '3.1'

services:
  postgres:
    image: postgres:10.5-alpine
    command: postgres -c 'max_connections=300'
    volumes:
      - ../volumes/pgdata/:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  redis:
    image: redis:4.0.11-alpine
    volumes:
      - ../volumes/redisdata/:/data
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 6379:6379

  rabbit:
    image: rabbitmq:3.7.8-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    deploy:
      restart_policy:
        condition: on-failure

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    environment:
      http.host: 0.0.0.0
      transport.host: 127.0.0.1
    ports:
      - 9200:9200
      - 9300:9300
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ../volumes/elasticsearch:/usr/share/elasticsearch/data