version: '3.4'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    environment:
      http.host: 0.0.0.0
      transport.host: 127.0.0.1
      ES_JAVA_OPTS: "-Xms300M -Xmx1536M"
    ports:
    - 9200:9200
    - 9300:9300
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 20
    volumes:
    - ../volumes/elasticsearch:/usr/share/elasticsearch/data

