actions:
  delete_indices_logstash:
    action: delete_indices
    description: >-
      Delete system indices older than 3 days (ignore_empty_list).
    options:
      ignore_empty_list: True
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-system
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: ${UNIT_COUNT}
      exclude: