spring:
  rabbitmq:
    host: ${rabbit.host}
    port: ${rabbit.port}
    stompPort: ${rabbit.stompPort}
    password: ${rabbit.password}
    username: ${rabbit.user}
    connection-timeout: 5s
    queue-logstash-system: LOG_SYSTEM_QUEUE
    queue-logstash-request: LOG_REQUEST_QUEUE