# serivce name
spring:
  application:
    name: permission-service
  mvc:
    logResolvedException: false

module-url: /permission/v1

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

server:
  port: 8230

db:
  schema: permission

security:
  properties:
    jwtHeader: Service-Authorization
    jwtPrefix: JWT
    jwtSecret: CnfxFqbCKHLqzT9LGruE

# eureka server url
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka
    registry-fetch-interval-seconds: 20
    availability-zones:
      default: defaultZone
    region: default
    enabled: true
  instance:
    prefer-ip-address: true

exchange:
  endpoint:
    account:
      userIsExist: http://account-service/user/exist
      getByPhone: http://account-service/user/by-phone
#      userKYCPassed: http://account-service/user/kyc-passed
