spring:
  datasource:
    url: jdbc:postgresql://46.101.182.178:26780/simia_db
    username: postgres
    password: GliesereumAdmin0013
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: ${db.schema}
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration/all,classpath:db/migration/data
    baseline-version: 1
    sql-migration-suffixes: .sql
    sql-migration-prefix: V
    schemas: ${db.schema}

  rabbitmq:
    host: 207.154.239.122
    port: 5672
    password: Af2f4dsASF
    username: rabbit
    queue-logstash-system: logstash-system
    queue-logstash-request: logstash-request
    queue-mail: verificationQueue
    connection-timeout: 5s

  data:
    jest:
      uris: http://207.154.239.122:9200
      max-connection-idle-time: 5000
      read-timeout: 5000

swagger:
  enable: true
